services:
    embeddings:
        model: "text-embedding-3-large"
        url: "https://api.openai.com/v1/embeddings"
    image_annotation:
        model: "meta-llama/llama-4-scout-17b-16e-instruct"
        url: "https://api.groq.com/openai/v1/chat/completions"
    summarizer:
        model: "llama-3.1-8b-instant"
        url: "https://api.groq.com/openai/v1/chat/completions"